# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.1.10-node

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - add-ssh-keys:
          fingerprints:
            - '2e:bc:dc:f9:ec:88:42:05:4d:b0:9e:ce:94:c7:05:d1'
      - checkout
      # Download and cache dependencies

      - run: yarn install --ignore-engines
      - run: gem install percy-cli

      # run export
      - run: yarn export
      # run visual diff testing
      - run: percy snapshot --widths "375,1280,1800" out/ --enable_javascript
      - deploy:
          name: Deploy GitHub Pages (Production)
          command: |
            if [ "${CIRCLE_BRANCH}" == "production" ]; then
              ./scripts/deploy-ghpages.sh build
            fi
